---
- name: Install mariadb-server
  ansible.builtin.package:
    name:
      - mariadb-server
    state: present

- name: Install MySQL-python
  ansible.builtin.package:
    name: python3-PyMySQL

- name: Create '/etc/my.cnf'
  ansible.builtin.template:
    src: my.cnf
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Start and enable mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  timeout: 20

- name: Check for socket in /etc/my.cnf
  ansible.builtin.shell: grep -m 1 'socket' /etc/my.cnf | awk -F'=' '{print $2}'
  register: socket_path_result
  changed_when: false
  ignore_errors: yes

- name: Check for socket in /etc/mysql/mariadb.conf.d/
  ansible.builtin.shell: grep -m 1 'socket' /etc/mysql/mariadb.conf.d/* | awk -F'=' '{print $2}'
  register: socket_path_conf_d
  changed_when: false
  ignore_errors: yes

- name: Determine Unix Socket path
  ansible.builtin.set_fact:
    unix_socket_path: "{{ socket_path_result.stdout | default(socket_path_conf_d.stdout) }}"

- name: Set root user password
  community.mysql.mysql_user:
    login_unix_socket: "{{ unix_socket_path }}"
    login_user: root
    login_password: ''
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    column_case_sensitive: true

- name: Remove anonymous user accounts
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: ''
    state: absent
    host_all: yes

- name: Delete test database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: test
    state: absent

- name: Restart mariadb service
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes
