---
- name: Enable the MariaDB repository
  ansible.builtin.yum_repository:
    name: mariadb
    file: MariaDB
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Install mariadb-devel and mariadb-server(CentOS7)
  ansible.builtin.yum:
    name:
      - MariaDB-devel
      - MariaDB-server
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Install mariadb-devel and mariadb-server(CentOS8)
  ansible.builtin.yum:
    name:
      - mariadb-server
      - mariadb-devel
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Install MySQL-python(CentOS7)
  ansible.builtin.yum:
    name: MySQL-python
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Install MySQL-python(CentOS8)
  ansible.builtin.yum:
    name: python3-PyMySQL
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Create '/etc/my.cnf'
  ansible.builtin.template:
    src: my.cnf
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Start and enable mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  timeout: 20

- name: Delete anonymous user
  community.mysql.mysql_user:
    name: ''
    state: absent

- name: Delete test database
  community.mysql.mysql_db:
    name: test
    state: absent

- name: Set root password
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Restart mariadb service
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes
